version: '3.7'

services:

  php:
    image: mariort/phpcli:8.1-dev
    volumes:
      - .:/app
    environment:
      - XDEBUG_MODE=off
      - XDEBUG_CONFIG
      - COMPOSER_AUTH
    networks: 
      - default
    # command: sh /app/docker/shell/php-cli.sh
    command: sh -c 'composer install && ./vendor/bin/behat'
    
networks:
  default:
    name: local